// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAGUhSda7sa96GOJqZXzVsdUIt5kHcVazQ',
    appId: '1:273466542453:web:a573bffafb87169dc26b3c',
    messagingSenderId: '273466542453',
    projectId: 'mshop-51107',
    authDomain: 'mshop-51107.firebaseapp.com',
    storageBucket: 'mshop-51107.appspot.com',
    measurementId: 'G-LB1W6N4YD3',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCql_SYx4GX5mkhzoS6c2M3io4Sobt_hjU',
    appId: '1:273466542453:android:b5ee0084f2cadfbac26b3c',
    messagingSenderId: '273466542453',
    projectId: 'mshop-51107',
    storageBucket: 'mshop-51107.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCxO4X95oS7nyIUiDBQ5xs_OtYHVSOZgFM',
    appId: '1:273466542453:ios:635a174b4ae05bc7c26b3c',
    messagingSenderId: '273466542453',
    projectId: 'mshop-51107',
    storageBucket: 'mshop-51107.appspot.com',
    iosBundleId: 'com.example.mshope',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCxO4X95oS7nyIUiDBQ5xs_OtYHVSOZgFM',
    appId: '1:273466542453:ios:635a174b4ae05bc7c26b3c',
    messagingSenderId: '273466542453',
    projectId: 'mshop-51107',
    storageBucket: 'mshop-51107.appspot.com',
    iosBundleId: 'com.example.mshope',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAGUhSda7sa96GOJqZXzVsdUIt5kHcVazQ',
    appId: '1:273466542453:web:77424f7297a73886c26b3c',
    messagingSenderId: '273466542453',
    projectId: 'mshop-51107',
    authDomain: 'mshop-51107.firebaseapp.com',
    storageBucket: 'mshop-51107.appspot.com',
    measurementId: 'G-Z0SYM4N4XC',
  );
}
